// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StduentCourseTableCrud.Data;

#nullable disable

namespace StduentCourseTableCrud.Migrations
{
    [DbContext(typeof(StudentCourseCRUD))]
    [Migration("20230502130516_strat carete")]
    partial class stratcarete
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StduentCourseTableCrud.Models.Domain.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Course_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("StduentCourseTableCrud.Models.Domain.Student", b =>
                {
                    b.Property<int>("Student_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Student_Id"));

                    b.Property<string>("Student_Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Student_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Student_Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Student_Id");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("StduentCourseTableCrud.Models.Domain.StudetCourse", b =>
                {
                    b.Property<int>("StudentCourse_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentCourse_Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int>("Student_Id")
                        .HasColumnType("int");

                    b.HasKey("StudentCourse_Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("Student_Id");

                    b.ToTable("StudentCourse");
                });

            modelBuilder.Entity("StduentCourseTableCrud.Models.Domain.StudetCourse", b =>
                {
                    b.HasOne("StduentCourseTableCrud.Models.Domain.Course", "Course")
                        .WithMany("Enroll")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StduentCourseTableCrud.Models.Domain.Student", "Student")
                        .WithMany("Enroll")
                        .HasForeignKey("Student_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("StduentCourseTableCrud.Models.Domain.Course", b =>
                {
                    b.Navigation("Enroll");
                });

            modelBuilder.Entity("StduentCourseTableCrud.Models.Domain.Student", b =>
                {
                    b.Navigation("Enroll");
                });
#pragma warning restore 612, 618
        }
    }
}
